### PR TITLE
Fixes #11 

### LINKED ISSUE #11: Error in ViewBatch.py
This BatchProfiler submission uses the current trunk build (20150910): 

```
http://imagewebrhel6/batchprofiler/cgi-bin/NewBatch.py?data_dir=%2Fimaging%2Fanalysis%2F2010_05_18_Malaria_Liver_Infection_Bhatia_Lab%2FAnalysis%2F2015_03_02_PV_20x_v5_2015_10_15
```

It apparently ran ok (at least it created the right amount of database Per_Image rows), but ViewBatch returns this error with this URL http://imagewebrhel6/batchprofiler/cgi-bin/ViewBatch.py?batch_id=68:

```
A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.

 /imaging/docs/People/imageweb/batchprofiler/BatchProfiler/ViewBatch.py in ()
    659         
    660 with bputilities.CellProfilerContext():
    661     doc = ViewBatchDoc()
=>  662     doc.build()
    663 doc.render()
doc = <bpformdata.ViewBatchDoc object>, doc.build = <bound method ViewBatchDoc.build of <bpformdata.ViewBatchDoc object>>
 /imaging/docs/People/imageweb/batchprofiler/BatchProfiler/ViewBatch.py in build(self=<bpformdata.ViewBatchDoc object>)
     66             self.build_submit_run()
     67         else:
=>   68             self.build_batch()
     69     
     70     def read_batch(self):
self = <bpformdata.ViewBatchDoc object>, self.build_batch = <bound method ViewBatchDoc.build_batch of <bpformdata.ViewBatchDoc object>>
 /imaging/docs/People/imageweb/batchprofiler/BatchProfiler/ViewBatch.py in build_batch(self=<bpformdata.ViewBatchDoc object>)
    201                 self.build_summary_table()
    202                 self.build_summary_buttons()
=>  203                 self.build_database_scripts()
    204             with self.tag("div", style='clear:both; padding-top:10px'):
    205                 self.build_job_table()
self = <bpformdata.ViewBatchDoc object>, self.build_database_scripts = <bound method ViewBatchDoc.build_database_scripts of <bpformdata.ViewBatchDoc object>>
 /imaging/docs/People/imageweb/batchprofiler/BatchProfiler/ViewBatch.py in build_database_scripts(self=<bpformdata.ViewBatchDoc object>)
    375                     run, task, task_status = sql_jobs.sql_file_job_and_status(
    376                         self.my_batch.batch_id, 
=>  377                         RunBatch.batch_script_file(filename))
    378                     status = None if task_status is None else task_status.status
    379                     with self.tag("tr"):
global RunBatch = <module 'RunBatch' from '/imaging/docs/People/imageweb/batchprofiler/BatchProfiler/RunBatch.py'>, RunBatch.batch_script_file = <function batch_script_file>, filename = 'SQL__Per_Well_SETUP.SQL'
 /imaging/docs/People/imageweb/batchprofiler/BatchProfiler/sql_jobs.py in sql_file_job_and_status(batch_id=68, sql_file='batch_SQL__Per_Well_SETUP.SQL')
     54     returns latest job or None if not submitted
     55     """
=>   56     batch = RunBatch.select(batch_id)
     57     run = RunBatch.BPSQLRun.select_by_sql_filename(batch, sql_file)
     58     if run is None:
batch undefined, global RunBatch = <module 'RunBatch' from '/imaging/docs/People/imageweb/batchprofiler/BatchProfiler/RunBatch.py'>, RunBatch.select undefined, batch_id = 68
<type 'exceptions.AttributeError'>: 'module' object has no attribute 'select' 
      args = ("'module' object has no attribute 'select'",) 
      message = "'module' object has no attribute 'select'"
```

@braymp have you run/tested any new CP versions since September?

### PR DESCRIPTION
**Pull request by LeeKamentsky**
There was a typo in the line that retrieved the batch info in the script that's responsible for keeping track of .SQL upload jobs.

### CODE REVIEW

**Comment by dlogan** [comment]
I would merge this**\* but either I can't because of the Travis failure or because I don't have permission -- not sure which.

**\* Shouldn't line 38 of sql_jobs.py also be changed from 

```
batch = RunBatch.select(batch_id)
```

to

```
batch = RunBatch.BPBatch.select(batch_id)
```

?
(I can make a pull request if Yes)

**Comment by LeeKamentsky** [comment]
It has to be because you don't have permission. Let me check on the error you found first though.

**Comment by LeeKamentsky** [comment]
@dlogan you should have permissions to merge now, Travis shouldn't be messing with BatchProfiler, hopefully that's turned off. Let me check the error you found. I think there may be some more edits too.

**Comment by dlogan** [comment]
Yup, I can see the PR button now, thanks (but I will wait).

**Comment by LeeKamentsky** [comment]
@dlogan ok it's fixed. Please hit the button.

**Comment by dlogan** [comment]
Do I need to 'git pull' in /imaging/docs/People/imageweb/batchprofiler/BatchProfiler to get these to changes to work for, say, http://imagewebrhel6/batchprofiler/cgi-bin/ViewBatch.py?batch_id=138
That page still gives me an error.

**Comment by LeeKamentsky** [comment]
It's probably not a good idea for you to do the git pull. I just had to fix up permissions because somehow the imageweb account had done that. But yes - I had to do exactly that to get it to update and you should be good now.

**Comment by dlogan** [comment]
awesome, thanks! I'll keep that in mind

**Pull request merged**
